spring:
  application:
    name: room-service		
  data:
    mongodb:
      host: localhost
      port: 28017
      database: room
      username: root
      password: root
      authentication-database: admin				
logging:
  level:
    root: INFO
    com.piseth.java.school: DEBUG		
room:
  seed:
    enabled: true
storage:
 minio:
   endpoint: http://localhost:9000
   accessKey: minioadmin
   secretKey: minioadmin
   bucket: room-media
   publicBaseUrl: http://localhost:9000
   maxFilesPerRoom: 10
   maxFileSizeBytes: 5000000   
server:
  port: 8057